### get employees
GET http://localhost:3000/api/employees

###
POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "name": "John Doe",
  "salary": 1000
}

### Get employee by id
GET http://localhost:3000/api/employees/2

### Update an employee
PATCH http://localhost:3000/api/employees/2
Content-Type: application/json

{
  "name": "Ryan Ray",
  "salary": 500
}

POST http://localhost:3001/api/Create
Content-Type: application/json

{
  "Nombre": "deisi",
  "ApellidoP": "doroteo",
  "ApellidoM": "martinez",
  "Correo": "juan@example.com",
  "Telefono": "7712153230",
  "Password": "password123",
  "FechaN": "1990-05-15"
}

